/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Auction_Management;

import Login.*;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.Color;
import javax.swing.JOptionPane;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextField;

public class EditUser extends javax.swing.JInternalFrame {
    String s = "update##person";
    Socket clientSocket;
    String username;
    DataOutputStream sendToServer;
    String string;
    
    public EditUser(Socket clientSocket, String username,String string, String name) {
        initComponents();
        jPanel.setVisible(false);
        this.clientSocket = clientSocket;
        this.string = string;
        this.username = username;
        
                String[] ss = string.split("##");
                
                    jTextFieldName.setText(ss[0]);
                    jTextFieldAge.setText(ss[1]);
                    jTextFieldGmail.setText(ss[2]);
                    jTextFieldAddress.setText(ss[3]);
                    jTextFieldPhone.setText(ss[4]);
                    jPasswordField.setText(ss[6]);
                    jTextFieldNationality.setText(ss[7]);
                    
                          
    }

    public String getjTextFieldName() {
        return jTextFieldName.getText();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelGmail = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelNationality = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldGmail = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldNationality = new javax.swing.JTextField();
        jButtonName = new javax.swing.JButton();
        jButtonAge = new javax.swing.JButton();
        jButtonGmail = new javax.swing.JButton();
        jButtonAddress = new javax.swing.JButton();
        jButtonPhone = new javax.swing.JButton();
        jButtonNationality = new javax.swing.JButton();
        jButtonPassword = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelUser = new javax.swing.JLabel();
        jCheckBoxShowPassword = new javax.swing.JCheckBox();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jPasswordFieldPasswordConfirm = new javax.swing.JPasswordField();
        jLabelConfirmError = new javax.swing.JLabel();
        jLabelNameError = new javax.swing.JLabel();
        jLabelAgeError = new javax.swing.JLabel();
        jLabelGmailError = new javax.swing.JLabel();
        jLabelAddressError = new javax.swing.JLabel();
        jLabelPhoneError = new javax.swing.JLabel();
        jLabelNationalityError = new javax.swing.JLabel();
        jLabelPasswordError = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelName.setText("Name:");

        jLabelAge.setText("Age:");

        jLabelGmail.setText("Gmail:");

        jLabelAddress.setText("Address:");

        jLabelPhone.setText("Phone Number:");

        jLabelNationality.setText("Nationality:");

        jLabelPassword.setText("Password:");

        jTextFieldName.setEnabled(false);
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldAge.setEnabled(false);
        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });

        jTextFieldGmail.setEnabled(false);
        jTextFieldGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGmailActionPerformed(evt);
            }
        });

        jTextFieldAddress.setEnabled(false);
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jTextFieldPhone.setEnabled(false);

        jTextFieldNationality.setEnabled(false);

        jButtonName.setText("Edit");
        jButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNameActionPerformed(evt);
            }
        });

        jButtonAge.setText("Edit");
        jButtonAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgeActionPerformed(evt);
            }
        });

        jButtonGmail.setText("Edit");
        jButtonGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGmailActionPerformed(evt);
            }
        });

        jButtonAddress.setText("Edit");
        jButtonAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddressActionPerformed(evt);
            }
        });

        jButtonPhone.setText("Edit");
        jButtonPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhoneActionPerformed(evt);
            }
        });

        jButtonNationality.setText("Edit");
        jButtonNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNationalityActionPerformed(evt);
            }
        });

        jButtonPassword.setText("Edit");
        jButtonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasswordActionPerformed(evt);
            }
        });

        jPasswordField.setEnabled(false);

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUser.setText("Change Info");

        jCheckBoxShowPassword.setText("Show Password");
        jCheckBoxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPasswordActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelConfirmPassword.setText("Confirm Password:");

        jPasswordFieldPasswordConfirm.setEnabled(false);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConfirmPassword)
                .addGap(32, 32, 32)
                .addComponent(jPasswordFieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabelConfirmError)
                .addGap(19, 19, 19))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmPassword)
                    .addComponent(jPasswordFieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConfirmError))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelGmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNationality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldAge)
                            .addComponent(jTextFieldGmail)
                            .addComponent(jTextFieldAddress)
                            .addComponent(jTextFieldPhone)
                            .addComponent(jTextFieldNationality)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonName)
                            .addComponent(jButtonAge)
                            .addComponent(jButtonGmail)
                            .addComponent(jButtonAddress)
                            .addComponent(jButtonPhone)
                            .addComponent(jButtonNationality)
                            .addComponent(jButtonPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButtonSave)
                        .addGap(69, 69, 69)
                        .addComponent(jButtonCancel))
                    .addComponent(jCheckBoxShowPassword)
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPasswordError)
                    .addComponent(jLabelNationalityError)
                    .addComponent(jLabelPhoneError)
                    .addComponent(jLabelAddressError)
                    .addComponent(jLabelGmailError)
                    .addComponent(jLabelAgeError)
                    .addComponent(jLabelNameError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelNameError)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAgeError)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGmailError)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAddressError)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPhoneError)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNationalityError)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPasswordError)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAge)
                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGmail)
                            .addComponent(jTextFieldGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddress)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddress))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhone)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPhone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNationality)
                            .addComponent(jTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNationality))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassword)
                            .addComponent(jButtonPassword)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxShowPassword)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSave)
                            .addComponent(jButtonCancel))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTextFieldGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGmailActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jButtonAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddressActionPerformed
        
        if(jTextFieldAddress.isEnabled()){
            jTextFieldAddress.setEnabled(false);
            jButtonAddress.setText("Edit");
                      
        }   else {
            jTextFieldAddress.setEnabled(true);
            jButtonAddress.setText("Change");
            jTextFieldAddress.setText("");
        }
    }//GEN-LAST:event_jButtonAddressActionPerformed

    private void jButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNameActionPerformed
        if(jTextFieldName.isEnabled()){
            jTextFieldName.setEnabled(false);
            jButtonName.setText("Edit");
        }   else {
            jTextFieldName.setEnabled(true);
            jButtonName.setText("Change");
        }
    }//GEN-LAST:event_jButtonNameActionPerformed

    private void jButtonAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgeActionPerformed
        if(jTextFieldAge.isEnabled()){
            jTextFieldAge.setEnabled(false);
            jButtonAge.setText("Edit");
        }   else {
            jTextFieldAge.setEnabled(true);
            jButtonAge.setText("Change");
        }
    }//GEN-LAST:event_jButtonAgeActionPerformed

    private void jButtonGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGmailActionPerformed
        if(jTextFieldGmail.isEnabled()){
            jTextFieldGmail.setEnabled(false);
            jButtonGmail.setText("Edit");
        }   else {
            jTextFieldGmail.setEnabled(true);
            jButtonGmail.setText("Change");
        }
    }//GEN-LAST:event_jButtonGmailActionPerformed

    private void jButtonPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhoneActionPerformed
        if(jTextFieldPhone.isEnabled()){
            jTextFieldPhone.setEnabled(false);
            jButtonPhone.setText("Edit");
        }   else {
            jTextFieldPhone.setEnabled(true);
            jButtonPhone.setText("Change");
        }
    }//GEN-LAST:event_jButtonPhoneActionPerformed

    private void jButtonNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNationalityActionPerformed
        if(jTextFieldNationality.isEnabled()){
            jTextFieldNationality.setEnabled(false);
            jButtonNationality.setText("Edit");
        }   else {
            jTextFieldNationality.setEnabled(true);
            jButtonNationality.setText("Change");
        }
    }//GEN-LAST:event_jButtonNationalityActionPerformed

    private void jButtonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasswordActionPerformed
        if(jPasswordField.isEnabled()){
            jPasswordField.setEnabled(false);
            jPasswordFieldPasswordConfirm.setEnabled(false);
            jButtonPassword.setText("Edit");
            jPanel.setVisible(false);
        }   else {
            jPasswordField.setEnabled(true);
            jPasswordFieldPasswordConfirm.setEnabled(true);
            jButtonPassword.setText("Change");
            jPanel.setVisible(true);
            
        }
    }//GEN-LAST:event_jButtonPasswordActionPerformed

    private void jCheckBoxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswordActionPerformed
        if(jCheckBoxShowPassword.isSelected()){
            jCheckBoxShowPassword.setText("Password is showing");
            jPasswordField.setEchoChar((char)0);
            jPasswordFieldPasswordConfirm.setEchoChar((char)0);
        } else {
            jCheckBoxShowPassword.setText("Password is hiding");
            jPasswordField.setEchoChar('*');
            jPasswordFieldPasswordConfirm.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPasswordActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButtonCancelActionPerformed
User user;
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if(!clientSocket.isConnected()){
            
            JOptionPane.showMessageDialog(this, "Can not connect with server");
            System.exit(0);
        }else{
        Register r = new Register();
        boolean checked = true;
        String name = jTextFieldName.getText(); 
        String age = jTextFieldAge.getText();
        String gmail = jTextFieldGmail.getText();
        String address = jTextFieldAddress.getText();
        String phoneNumber = jTextFieldPhone.getText();
        String nationality =  jTextFieldNationality.getText();
        String passwordText = new String(jPasswordField.getPassword());        
        String passwordConfirm = new String(jPasswordFieldPasswordConfirm.getPassword());
        
        
        
        jLabelNameError.setForeground(Color.red);
        jLabelAgeError.setForeground(Color.red);
        jLabelGmailError.setForeground(Color.red);
        jLabelAddressError.setForeground(Color.red);
        jLabelPhoneError.setForeground(Color.red);
        jLabelPasswordError.setForeground(Color.red);
        jLabelConfirmError.setForeground(Color.red);
        jLabelNationalityError.setForeground(Color.red);
        
        
        try {
            sendToServer = new DataOutputStream(clientSocket.getOutputStream()); // Tao output stream ket noi toi socket
//            sendToServer.writeBytes("select##person\n");// gui toi server
            BufferedReader inFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));

//            while (true) {
//
//                String ketQua = inFromServer.readLine();// Nhan lai tu server
//                if (ketQua.equals("quit")) {
//                    break;
//                }
//                String[] ss = ketQua.split("##");
            if(!r.checkIsString(name)|| r.checkIsEmpty(name)){
                checked =false;
                jLabelNameError.setText("Error!!!");
                s = "update##person";
            } else {
                name = r.editSpaceOrUpperCase(name);
                jLabelNameError.setText("");
                s += "##"+name;
                
            }

            if(!r.checkIsAge(age) || r.checkIsEmpty(age) ){
                checked =false;
                jLabelAgeError.setText("Error!!!");
                s = "update##person";
            } else {
                jLabelAgeError.setText("");
                s += "##"+age;
                
            }

            if(!r.checkIsMail(gmail) || r.checkIsEmpty(gmail)){
               checked =false;
               jLabelGmailError.setText("Error!!!");
               s = "update##person";
            } else {
               jLabelGmailError.setText("");
               s += "##"+gmail;
              
            }

            if(!r.checkIsAddress(address) || r.checkIsEmpty(address)){
                checked =false;
                jLabelAddressError.setText("Error!!!");
                s = "update##person";
            } else {
                address = r.editSpaceOrUpperCase(address);
                jLabelAddressError.setText("");
                s += "##"+address;
              
            }

            if(!r.checkIsPhoneNumber(phoneNumber) || r.checkIsEmpty(phoneNumber)){
                checked =false;
                jLabelPhoneError.setText("Error!!!");
                s = "update##person";
            } else {

                jLabelPhoneError.setText("");
                s += "##"+phoneNumber;
           
            }

            if(!r.checkIsPassWord(passwordText) || r.checkIsEmpty(passwordText)){
                checked =false;
                jLabelPasswordError.setText("Error!!!");
                s = "update##person";
            } else {
                jLabelPasswordError.setText("");
                s += "##"+passwordText;
                
            }

            if(!r.checkIsAddress(nationality) || r.checkIsEmpty(nationality)){
                checked =false;
                jLabelNationalityError.setText("Error!!!");
                s = "update##person";
            } else {
                nationality = r.editSpaceOrUpperCase(nationality);
                jLabelNationalityError.setText("");
                s += "##"+nationality;
                
            }

            if(!passwordConfirm.equals(passwordText) || r.checkIsEmpty(passwordConfirm)){
                checked = false;
                jLabelConfirmError.setText("Error!!!");
                s = "update##person";
            } else {
                jLabelConfirmError.setText("");
            }


            if(checked){
    //            new User().setVisible(true);
                s += "##"+ username;
                sendToServer.writeBytes(s+'\n');
                sendToServer.writeBytes("update##name##UserManagement##"+name+"##"+username+"\n");
                this.dispose();          
                JOptionPane.showMessageDialog(rootPane,"\nUpdate Successful"); 
            }else{
                JOptionPane.showMessageDialog(rootPane,"\nUpdate Unsuccessful"); 
            }
//        }
        
        } catch (IOException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed
    
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if(!clientSocket.isConnected()){
            try {
                clientSocket.close();
            } catch (IOException ex) {
                Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddress;
    private javax.swing.JButton jButtonAge;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonGmail;
    private javax.swing.JButton jButtonName;
    private javax.swing.JButton jButtonNationality;
    private javax.swing.JButton jButtonPassword;
    private javax.swing.JButton jButtonPhone;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxShowPassword;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAddressError;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelAgeError;
    private javax.swing.JLabel jLabelConfirmError;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelGmail;
    private javax.swing.JLabel jLabelGmailError;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameError;
    private javax.swing.JLabel jLabelNationality;
    private javax.swing.JLabel jLabelNationalityError;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPasswordError;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhoneError;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldPasswordConfirm;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldGmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNationality;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
