/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Auction_Management;

import Login.*;
import info_Product.ProductBought;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author icydeath
 */
public class History extends javax.swing.JFrame {

   DefaultTableModel model;
     String localhost;
     Socket clientSocket;
     String username;
    /**
     * Creates new form History
     */
    public History(Socket clientSocket, String username,String localhost) {
        initComponents();
        this.localhost = localhost;
        st(jTable1, jTextFieldSearch);
        jLabelDateTime.setText(getDate());
        
        this.username = username;
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //        model.removeRow(WIDTH);
        String s = "SELECT##productBought";
        
        try {
            String ketQua;//Cau duoc server xu ly va tra lai la in hoa
            this.clientSocket = new Socket(localhost, 9999);// Tao clinent socket de ket noi toi server  
            DataOutputStream sendToServer = new DataOutputStream(clientSocket.getOutputStream());// Tao output stream ket noi toi socket
            BufferedReader inFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            sendToServer.writeBytes(s+'\n');// gui toi server
            while (true) {

                ketQua = inFromServer.readLine();// Nhan lai tu server
                if (ketQua.equals("quit")) {
                    break;
                }
                String[] ss = ketQua.split("##");
                if(username.equals(ss[6])){
                    
                    model.addRow(new String[]{ss[0],ss[2],ss[4],ss[5],ss[7],ss[6]});
                }

            }
            //            clientSocket.close();//Dong ket noi
        } catch (IOException e) {
            System.out.println("Exception Client: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDateTime = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabelSearch = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButtonSell = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelDateTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDateTime.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDateTime.setText("Date");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setText(" History");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product", "Price", "Buyer", "Date", "Seller"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRefresh.setText("Buy");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jLabelSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearch.setText("Search:");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonSell.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonSell.setText("Sell");
        jButtonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTitle))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearch)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonSell))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //        model.removeRow(WIDTH);
        String s = "SELECT##productBought";
        try {
            String ketQua;//Cau duoc server xu ly va tra lai la in hoa
            DataOutputStream sendToServer = new DataOutputStream(clientSocket.getOutputStream());// Tao output stream ket noi toi socket
            BufferedReader inFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            sendToServer.writeBytes(s+'\n');// gui toi server
            while (true) {

                ketQua = inFromServer.readLine();// Nhan lai tu server
                if (ketQua.equals("quit")) {
                    break;
                }
                String[] ss = ketQua.split("##");
                if(username.equals(ss[5])){
                    
                    model.addRow(new String[]{ss[0],ss[2],ss[4],ss[5],ss[7],ss[6]});
                }

            }
            //            clientSocket.close();//Dong ket noi
        } catch (IOException e) {
            System.out.println("Exception Client: " + e.getMessage());
        }

        //        client(s);

    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       try {
           // TODO add your handling code here:

           clientSocket.close();
       } catch (IOException ex) {
           Logger.getLogger(History.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
    }//GEN-LAST:event_formWindowClosed
    ProductBought pro;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            if(pro == null || !pro.isVisible()){
                pro = new ProductBought(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString(),localhost);
                pro.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //        model.removeRow(WIDTH);
        String s = "SELECT##productBought";
        try {
            String ketQua;//Cau duoc server xu ly va tra lai la in hoa
            DataOutputStream sendToServer = new DataOutputStream(clientSocket.getOutputStream());// Tao output stream ket noi toi socket
            BufferedReader inFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
            sendToServer.writeBytes(s+'\n');// gui toi server
            while (true) {

                ketQua = inFromServer.readLine();// Nhan lai tu server
                if (ketQua.equals("quit")) {
                    break;
                }
                String[] ss = ketQua.split("##");
                if(username.equals(ss[6])){
                    
                    model.addRow(new String[]{ss[0],ss[2],ss[4],ss[5],ss[7],ss[6]});
                }

            }
            //            clientSocket.close();//Dong ket noi
        } catch (IOException e) {
            System.out.println("Exception Client: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSellActionPerformed
public void st(JTable searchTable, JTextField searchText){
        
        
        TableRowSorter<TableModel> Sorter = new TableRowSorter<>(searchTable.getModel());
        searchTable.setRowSorter(Sorter);
        searchText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = searchText.getText();
                if(text.length()==0){
                    Sorter.setRowFilter(null);
                } else {
                    Sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = searchText.getText();

                if (text.length() == 0) {
                    Sorter.setRowFilter(null);
                } else {
                    Sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    
    
    public String getDate(){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String dateString = dateFormat.format(date);
        return dateString;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSell;
    private javax.swing.JLabel jLabelDateTime;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
