/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author icydeath
 */
public class RegisterUser extends javax.swing.JFrame {
    String s = "insert##person";
    Socket clientSocket;
    String localhost;
    /**
     * Creates new form RegisterUser
     */
    Register r ;
    public RegisterUser(Socket clientSocket,String localhost) {
        initComponents();
        this.clientSocket = clientSocket;
        this.localhost = localhost;
        jLabelCaptchaResult.setText(r.createCaptchaValue());
//        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelGmail = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jLabelCaptcha = new javax.swing.JLabel();
        jLabelNationality = new javax.swing.JLabel();
        jCheckBoxAgree = new javax.swing.JCheckBox();
        jButtonRegister = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelEnterCaptcha = new javax.swing.JLabel();
        jTextFieldEnterCaptcha = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldGmail = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jPasswordFieldConfirmPassword = new javax.swing.JPasswordField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldNationality = new javax.swing.JTextField();
        jLabelCaptchaResult = new javax.swing.JLabel();
        jLabelNameError = new javax.swing.JLabel();
        jLabelAgeError = new javax.swing.JLabel();
        jLabelGmailError = new javax.swing.JLabel();
        jLabelAdressError = new javax.swing.JLabel();
        jLabelPhoneError = new javax.swing.JLabel();
        jLabelUserError = new javax.swing.JLabel();
        jLabelPasswordError = new javax.swing.JLabel();
        jLabelConfirmPasswordError = new javax.swing.JLabel();
        jLabelNationalityError = new javax.swing.JLabel();
        jLabelCaptchaError = new javax.swing.JLabel();
        jCheckBoxShowPassword = new javax.swing.JCheckBox();

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setText("Register account");

        jLabelName.setText("Name");

        jLabelAge.setText("Age");

        jLabelGmail.setText("Gmail");

        jLabelAddress.setText("Address");

        jLabelPhone.setText("Phone number");

        jLabelUsername.setText("Username");

        jLabelPassword.setText("Password");

        jLabelConfirmPassword.setText("Confirm password");

        jLabelCaptcha.setText("Captcha");

        jLabelNationality.setText("Nationality");

        jCheckBoxAgree.setText("I agree with the terms of use");
        jCheckBoxAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAgreeActionPerformed(evt);
            }
        });

        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelEnterCaptcha.setText("Enter captcha");

        jTextFieldGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGmailActionPerformed(evt);
            }
        });

        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });

        jTextFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNameMousePressed(evt);
            }
        });
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jTextFieldNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNationalityActionPerformed(evt);
            }
        });

        jCheckBoxShowPassword.setText("Show Password");
        jCheckBoxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPhone)
                                .addComponent(jLabelCaptcha)
                                .addComponent(jLabelAddress)
                                .addComponent(jLabelGmail)
                                .addComponent(jLabelAge)
                                .addComponent(jLabelName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(jTextFieldAddress)
                                .addComponent(jTextFieldGmail)
                                .addComponent(jTextFieldAge)
                                .addComponent(jTextFieldName)
                                .addComponent(jLabelCaptchaResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNameError, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(jLabelAgeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelGmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAdressError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPhoneError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPassword)
                                            .addComponent(jLabelUsername))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPasswordFieldPassword)
                                            .addComponent(jTextFieldUsername)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelConfirmPassword)
                                            .addComponent(jLabelEnterCaptcha))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPasswordFieldConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEnterCaptcha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelNationality)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jCheckBoxShowPassword))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelUserError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelConfirmPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNationalityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCaptchaError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(350, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxAgree)
                        .addGap(81, 81, 81))))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jButtonRegister)
                .addGap(46, 46, 46)
                .addComponent(jButtonCancel)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(jCheckBoxAgree)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegister)
                    .addComponent(jButtonCancel))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAge)
                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAgeError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGmail)
                            .addComponent(jTextFieldGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddress)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdressError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhone)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhoneError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCaptcha)
                            .addComponent(jLabelCaptchaResult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUserError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelUsername)
                                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPassword)
                                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelConfirmPassword)
                                .addComponent(jPasswordFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelConfirmPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jCheckBoxShowPassword)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelNationality)
                                .addComponent(jTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelNationalityError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEnterCaptcha)
                            .addComponent(jTextFieldEnterCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCaptchaError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAgreeActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGmailActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    public boolean isWrong(boolean checked){
            
        return checked;
    }
    
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        if(clientSocket.isConnected()){        
        r = new Register();
        boolean checked = true;
        String  name,
                age,
                gmail,
                address,
                phoneNumber,
                userName,
                passwordText,
                passwordConfirm,
                nationality;
        
        name = jTextFieldName.getText(); 
        age = jTextFieldAge.getText();
        gmail = jTextFieldGmail.getText();
        address = jTextFieldAddress.getText();
        phoneNumber = jTextFieldPhone.getText();
        userName = jTextFieldUsername.getText();
        passwordText = new String(jPasswordFieldPassword.getPassword());        
        passwordConfirm = new String(jPasswordFieldConfirmPassword.getPassword());
        nationality =  jTextFieldNationality.getText();

        jLabelNameError.setForeground(Color.red);
        jLabelAgeError.setForeground(Color.red);
        jLabelGmailError.setForeground(Color.red);
        jLabelAdressError.setForeground(Color.red);
        jLabelPhoneError.setForeground(Color.red);
        jLabelUserError.setForeground(Color.red);
        jLabelPasswordError.setForeground(Color.red);
        jLabelConfirmPasswordError.setForeground(Color.red);
        jLabelNationalityError.setForeground(Color.red);
        jLabelCaptchaError.setForeground(Color.red);
        
        if(!r.checkIsString(name)|| r.checkIsEmpty(name)){
            checked =false;
            jLabelNameError.setText("Error!!!");
            
        } else {
            name = r.editSpaceOrUpperCase(name);
            jLabelNameError.setText("");
        }
        
        if(!r.checkIsAge(age) || r.checkIsEmpty(age) ){
            checked =false;
            jLabelAgeError.setText("Error!!!");
        } else {
            jLabelAgeError.setText("");
        }
         
        if(!r.checkIsMail(gmail) || r.checkIsEmpty(gmail)){
           checked =false;
           jLabelGmailError.setText("Error!!!");
        } else {
           jLabelGmailError.setText("");
        }
        
        if(!r.checkIsString(address) || r.checkIsEmpty(address)){
            checked =false;
            jLabelAdressError.setText("Error!!!");
        } else {
            address = r.editSpaceOrUpperCase(address);
            jLabelAdressError.setText("");
        }

        if(!r.checkIsPhoneNumber(phoneNumber) || r.checkIsEmpty(phoneNumber)){
            checked =false;
            jLabelPhoneError.setText("Error!!!");
        } else {
            jLabelPhoneError.setText("");
        }
        
        if(!r.checkIsUser(userName) || r.checkIsEmpty(userName)){
            checked =false;
            jLabelUserError.setText("Error!!!");
        } else {
            jLabelUserError.setText("");
        }
        
        if(!r.checkIsPassWord(passwordText) || r.checkIsEmpty(passwordText)){
            checked =false;
            jLabelPasswordError.setText("Error!!!");
        } else {
            jLabelPasswordError.setText("");
        }
        
        if(!r.checkIsString(nationality) || r.checkIsEmpty(nationality)){
            checked =false;
            jLabelNationalityError.setText("Error!!!");
        } else {
            nationality = r.editSpaceOrUpperCase(nationality);
            jLabelNationalityError.setText("");
        }

        if(!passwordConfirm.equals(passwordText) || r.checkIsEmpty(passwordConfirm)){
            checked = false;
            jLabelConfirmPasswordError.setText("Error!!!");
        } else {
            jLabelConfirmPasswordError.setText("");
        }
     
        
        if(!jTextFieldEnterCaptcha.getText().equals(jLabelCaptchaResult.getText())){
            checked =false;
            jLabelCaptchaError.setText("Error!!!");
        } else {
            jLabelCaptchaError.setText("");
        }
        
        if(!jCheckBoxAgree.isSelected()){
            checked = false;
            JOptionPane.showMessageDialog(rootPane, "You must selected this to be accepted");
        }
 
        if(checked){
            DataOutputStream sendToServer = null;
            try {
                sendToServer = new DataOutputStream(clientSocket.getOutputStream()); // Tao output stream ket noi toi socket
                sendToServer.writeBytes("select##person\n");// gui toi server
                BufferedReader inFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
                ArrayList<String> arrayString = new ArrayList<String>();
                boolean checkDuplicated = true;
                while (true) {
                    
                    String ketQua = inFromServer.readLine();// Nhan lai tu server
                    if (ketQua.equals("quit")) {
                        break;
                    }
                    String[] ss = ketQua.split("##");
                    arrayString.add(ss[5]);
                }
                for(int i=0;i<arrayString.size();i++){
                    if(arrayString.get(i).equals(userName.trim())){
                        checkDuplicated = false;
//                        new Login().setVisible(true);
//                        this.dispose();
                        JOptionPane.showMessageDialog(rootPane,"Account already exists");
                        break;
                    }
                }
                if(checkDuplicated){
                    s = s + "##'" + name +
                        "'##" + age +
                        "##'" + gmail +
                        "'##'" + address +
                        "'##'" +phoneNumber+
                        "'##'" +userName +
                        "'##'" + passwordText +
                        "'##'" + nationality+"'";
                
                    sendToServer.writeBytes(s+'\n');// gui toi server
//                    new Login().setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(rootPane,"Register Successful");
                }
                
                
            } catch (IOException ex) {
                Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }}
        else{
            JOptionPane.showMessageDialog(this, "Can not connect with server");
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

  
    private void jTextFieldNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseExited
 

    }//GEN-LAST:event_jTextFieldNameMouseExited

    private void jTextFieldNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameMouseClicked

    private void jTextFieldNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMousePressed
        
    }//GEN-LAST:event_jTextFieldNameMousePressed

    private void jTextFieldNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseEntered
      
    }//GEN-LAST:event_jTextFieldNameMouseEntered

    private void jTextFieldNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNationalityActionPerformed

    private void jCheckBoxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswordActionPerformed
        if(jCheckBoxShowPassword.isSelected()){
            jCheckBoxShowPassword.setText("Password is showing");
            jPasswordFieldPassword.setEchoChar((char)0);
            jPasswordFieldConfirmPassword.setEchoChar((char)0);
        } else {
            jCheckBoxShowPassword.setText("Password is hiding");
            jPasswordFieldPassword.setEchoChar('*');
            jPasswordFieldConfirmPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPasswordActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
//        new Login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonCancelActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JCheckBox jCheckBoxAgree;
    private javax.swing.JCheckBox jCheckBoxShowPassword;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAdressError;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelAgeError;
    private javax.swing.JLabel jLabelCaptcha;
    private javax.swing.JLabel jLabelCaptchaError;
    private javax.swing.JLabel jLabelCaptchaResult;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelConfirmPasswordError;
    private javax.swing.JLabel jLabelEnterCaptcha;
    private javax.swing.JLabel jLabelGmail;
    private javax.swing.JLabel jLabelGmailError;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameError;
    private javax.swing.JLabel jLabelNationality;
    private javax.swing.JLabel jLabelNationalityError;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPasswordError;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhoneError;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUserError;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordFieldConfirmPassword;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEnterCaptcha;
    private javax.swing.JTextField jTextFieldGmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNationality;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
